### PR TITLE
Update domain references to ofa.us

### PR DESCRIPTION
**Pull request by camdenlee**
Hello @lorn and @nickcatal,

This PR updates a few domain references to ofa.us. These changes will need to go into OFA's version of Connect as well.

Let me know if you have any questions.

Camden

### CODE REVIEW

**Comment by j-ro** [comment]
Good here! @lorn wanna merge?

**Comment by lorn** [comment]
Hi @camdenlee, it's everything ok for me.
Do you plan to add more stuff? I saw the `in progress` label on the PR.

**Comment by nickcatal** [comment]
Looks good to me.

**Comment by camdenlee** [comment]
I didn't plan to add any more changes on open connect. Not sure how that
label was added.

Thanks, all.

**Pull request merged**
